using System;
namespace API.Entities
{
    public class Languages
    {
        public string Ara { get; set; }
        public string Cal { get; set; }
        public string Cha { get; set; }
        public string Eng { get; set; }
        public string Srp { get; set; }
        public string Cat { get; set; }
        public string Aym { get; set; }
        public string Grn { get; set; }
        public string Que { get; set; }
        public string Spa { get; set; }
        public string Fra { get; set; }
        public string Hye { get; set; }
        public string Mfe { get; set; }
        public string Div { get; set; }
        public string Smo { get; set; }
        public string Mkd { get; set; }
        public string Amh { get; set; }
        public string Kal { get; set; }
        public string Arc { get; set; }
        public string Ckb { get; set; }
        public string Nld { get; set; }
        public string Swe { get; set; }
        public string Est { get; set; }
        public string Bwg { get; set; }
        public string Kck { get; set; }
        public string Khi { get; set; }
        public string Ndc { get; set; }
        public string Nde { get; set; }
        public string Nya { get; set; }
        public string Sna { get; set; }
        public string Sot { get; set; }
        public string Toi { get; set; }
        public string Tsn { get; set; }
        public string Tso { get; set; }
        public string Ven { get; set; }
        public string Xho { get; set; }
        public string Zib { get; set; }
        public string Slk { get; set; }
        public string Prs { get; set; }
        public string Pus { get; set; }
        public string Tuk { get; set; }
        public string Sag { get; set; }
        public string Ita { get; set; }
        public string Lat { get; set; }
        public string Bis { get; set; }
        public string Gil { get; set; }
        public string Zho { get; set; }
        public string Por { get; set; }
        public string Tet { get; set; }
        public string Ssw { get; set; }
        public string Rus { get; set; }
        public string Uzb { get; set; }
        public string Ind { get; set; }
        public string Hrv { get; set; }
        public string Pol { get; set; }
        public string Bos { get; set; }
        public string Heb { get; set; }
        public string Pap { get; set; }
        public string Msa { get; set; }
        public string Mlt { get; set; }
        public string Bel { get; set; }
        public string Tur { get; set; }
        public string Fin { get; set; }
        public string Dzo { get; set; }
        public string Ces { get; set; }
        public string Cnr { get; set; }
        public string Nor { get; set; }
        public string Hin { get; set; }
        public string Tam { get; set; }
        public string Mri { get; set; }
        public string Nzs { get; set; }
        public string Jam { get; set; }
        public string Kon { get; set; }
        public string Lin { get; set; }
        public string Urd { get; set; }
        public string Kaz { get; set; }
        public string Fij { get; set; }
        public string Hif { get; set; }
        public string Isl { get; set; }
        public string Mya { get; set; }
        public string Ben { get; set; }
        public string Fil { get; set; }
        public string Gle { get; set; }
        public string Nep { get; set; }
        public string Kor { get; set; }
        public string Dan { get; set; }
        public string Tir { get; set; }
        public string Fas { get; set; }
        public string Swa { get; set; }
        public string Ell { get; set; }
        public string Nfr { get; set; }
        public string Kin { get; set; }
        public string Tvl { get; set; }
        public string Crs { get; set; }
        public string Khm { get; set; }
        public string Ukr { get; set; }
        public string Nau { get; set; }
        public string Afr { get; set; }
        public string Deu { get; set; }
        public string Her { get; set; }
        public string Hgm { get; set; }
        public string Kwn { get; set; }
        public string Loz { get; set; }
        public string Ndo { get; set; }
        public string Ton { get; set; }
        public string Mah { get; set; }
        public string De { get; set; }
        public string Hun { get; set; }
        public string Bjz { get; set; }
        public string Ltz { get; set; }
        public string Fao { get; set; }
        public string Lua { get; set; }
        public string Nbl { get; set; }
        public string Nso { get; set; }
        public string Zul { get; set; }
        public string Sin { get; set; }
        public string Lav { get; set; }
        public string Ron { get; set; }
        public string Mon { get; set; }
        public string Nno { get; set; }
        public string Nob { get; set; }
        public string Smi { get; set; }
        public string Tha { get; set; }
        public string Nrf { get; set; }
        public string Lao { get; set; }
        public string Aze { get; set; }
        public string Ber { get; set; }
        public string Bul { get; set; }
        public string Run { get; set; }
        public string Sqi { get; set; }
        public string Kat { get; set; }
        public string Vie { get; set; }
        public string Mey { get; set; }
        public string Jpn { get; set; }
        public string Lit { get; set; }
        public string Hat { get; set; }
        public string Hmo { get; set; }
        public string Tpi { get; set; }
        public string Kir { get; set; }
        public string Pau { get; set; }
        public string Mlg { get; set; }
        public string Tkl { get; set; }
        public string Slv { get; set; }
        public string Som { get; set; }
        public string Rar { get; set; }
        public string Zdj { get; set; }
        public string Niu { get; set; }
        public string Gsw { get; set; }
        public string Roh { get; set; }
        public string Pih { get; set; }
        public string Glv { get; set; }
        public string Tgk { get; set; }
        public string Pov { get; set; }
    }
}

