using System;
namespace API.Entities
{
    public class NativeName
    {
        public Ara Ara { get; set; }
        public Cal Cal { get; set; }
        public Cha Cha { get; set; }
        public Eng Eng { get; set; }
        public Srp Srp { get; set; }
        public Cat Cat { get; set; }
        public Aym Aym { get; set; }
        public Grn Grn { get; set; }
        public Que Que { get; set; }
        public Spa Spa { get; set; }
        public Fra Fra { get; set; }
        public Hye Hye { get; set; }
        public Mfe Mfe { get; set; }
        public Div Div { get; set; }
        public Smo Smo { get; set; }
        public Mkd Mkd { get; set; }
        public Amh Amh { get; set; }
        public Kal Kal { get; set; }
        public Arc Arc { get; set; }
        public Ckb Ckb { get; set; }
        public Nld Nld { get; set; }
        public Swe Swe { get; set; }
        public Est Est { get; set; }
        public Bwg Bwg { get; set; }
        public Kck Kck { get; set; }
        public Khi Khi { get; set; }
        public Ndc Ndc { get; set; }
        public Nde Nde { get; set; }
        public Nya Nya { get; set; }
        public Sna Sna { get; set; }
        public Sot Sot { get; set; }
        public Toi Toi { get; set; }
        public Tsn Tsn { get; set; }
        public Tso Tso { get; set; }
        public Ven Ven { get; set; }
        public Xho Xho { get; set; }
        public Zib Zib { get; set; }
        public Slk Slk { get; set; }
        public Prs Prs { get; set; }
        public Pus Pus { get; set; }
        public Tuk Tuk { get; set; }
        public Sag Sag { get; set; }
        public Ita Ita { get; set; }
        public Lat Lat { get; set; }
        public Bis Bis { get; set; }
        public Gil Gil { get; set; }
        public Zho Zho { get; set; }
        public Por Por { get; set; }
        public Tet Tet { get; set; }
        public Ssw Ssw { get; set; }
        public Rus Rus { get; set; }
        public Uzb Uzb { get; set; }
        public Ind Ind { get; set; }
        public Hrv Hrv { get; set; }
        public Pol Pol { get; set; }
        public Bos Bos { get; set; }
        public Heb Heb { get; set; }
        public Pap Pap { get; set; }
        public Msa Msa { get; set; }
        public Mlt Mlt { get; set; }
        public Bel Bel { get; set; }
        public Tur Tur { get; set; }
        public Fin Fin { get; set; }
        public Dzo Dzo { get; set; }
        public Ces Ces { get; set; }
        public Cnr Cnr { get; set; }
        public Nor Nor { get; set; }
        public Hin Hin { get; set; }
        public Tam Tam { get; set; }
        public Mri Mri { get; set; }
        public Nzs Nzs { get; set; }
        public Jam Jam { get; set; }
        public Kon Kon { get; set; }
        public Lin Lin { get; set; }
        public Urd Urd { get; set; }
        public Kaz Kaz { get; set; }
        public Fij Fij { get; set; }
        public Hif Hif { get; set; }
        public Isl Isl { get; set; }
        public Mya Mya { get; set; }
        public Ben Ben { get; set; }
        public Fil Fil { get; set; }
        public Gle Gle { get; set; }
        public Nep Nep { get; set; }
        public Kor Kor { get; set; }
        public Dan Dan { get; set; }
        public Tir Tir { get; set; }
        public Fas Fas { get; set; }
        public Swa Swa { get; set; }
        public Ell Ell { get; set; }
        public Nfr Nfr { get; set; }
        public Kin Kin { get; set; }
        public Tvl Tvl { get; set; }
        public Crs Crs { get; set; }
        public Khm Khm { get; set; }
        public Ukr Ukr { get; set; }
        public Nau Nau { get; set; }
        public Afr Afr { get; set; }
        public Deu Deu { get; set; }
        public Her Her { get; set; }
        public Hgm Hgm { get; set; }
        public Kwn Kwn { get; set; }
        public Loz Loz { get; set; }
        public Ndo Ndo { get; set; }
        public Ton Ton { get; set; }
        public Mah Mah { get; set; }
        public Bar Bar { get; set; }
        public Hun Hun { get; set; }
        public Bjz Bjz { get; set; }
        public Ltz Ltz { get; set; }
        public Fao Fao { get; set; }
        public Lua Lua { get; set; }
        public Nbl Nbl { get; set; }
        public Nso Nso { get; set; }
        public Zul Zul { get; set; }
        public Sin Sin { get; set; }
        public Lav Lav { get; set; }
        public Ron Ron { get; set; }
        public Mon Mon { get; set; }
        public Nno Nno { get; set; }
        public Nob Nob { get; set; }
        public Smi Smi { get; set; }
        public Tha Tha { get; set; }
        public Nrf Nrf { get; set; }
        public Lao Lao { get; set; }
        public Aze Aze { get; set; }
        public Ber Ber { get; set; }
        public Bul Bul { get; set; }
        public Run Run { get; set; }
        public Sqi Sqi { get; set; }
        public Kat Kat { get; set; }
        public Vie Vie { get; set; }
        public Mey Mey { get; set; }
        public Jpn Jpn { get; set; }
        public Lit Lit { get; set; }
        public Hat Hat { get; set; }
        public Hmo Hmo { get; set; }
        public Tpi Tpi { get; set; }
        public Kir Kir { get; set; }
        public Pau Pau { get; set; }
        public Mlg Mlg { get; set; }
        public Tkl Tkl { get; set; }
        public Slv Slv { get; set; }
        public Som Som { get; set; }
        public Rar Rar { get; set; }
        public Zdj Zdj { get; set; }
        public Niu Niu { get; set; }
        public Gsw Gsw { get; set; }
        public Roh Roh { get; set; }
        public Pih Pih { get; set; }
        public Glv Glv { get; set; }
        public Tgk Tgk { get; set; }
        public Pov Pov { get; set; }
    }
}

